USE college;

CREATE TABLE IF NOT EXISTS Students(
StudentID INT PRIMARY KEY,
Name VARCHAR(100),
Email VARCHAR(50),
CGPA DECIMAL(3,2),
Phone VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS instructors(
instructorID INT PRIMARY KEY,
Name VARCHAR(200),
Gender VARCHAR(10),
StartTime TIME,
EndTime TIME,
Phone VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS college_employee(
employeeID INT PRIMARY KEY,
name VARCHAR(100),
salary DECIMAL(10,2),
`rank` VARCHAR(200), -- RANK IS THE RESERVED WORD FOR WINDOW FUNCTION SO I USE BACKTICKS ` `
city VARCHAR(20),
officeHour VARCHAR(50)
);
